{
  'targets': [
    {
      'target_name': 'go-addon',
      # import all necessary source files
      'sources': [
        'lib/libgo.h', # this file was generated by go build
        'goAddon.cc'
      ],
      # libraries are relative to the 'build' directory
      'libraries': [ '../lib/libgo.a' ] # this file was also generated by go build
    }
  ]
}