---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-volumeclaim

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "mongodb"
  labels:
    app: "mongodb"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "mongodb"
  template:
    metadata:
      labels:
        app: "mongodb"
    spec:
      containers:
      - name: "mongo"
        image: "mongo:3.2.11"
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-volumeclaim

---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongodb-service"
  labels:
    app: "mongodb"
spec:
  ports:
  - protocol: "TCP"
    port: 27017
    targetPort: 27017
  selector:
    app: "mongodb"
  type: "ClusterIP"