/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	String_comparison_exp:{
		_eq:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_ilike:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		_iregex:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_is_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_like:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nilike:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		_niregex:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nlike:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nregex:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nsimilar:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_regex:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_similar:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	follows_aggregate_fields:{
		count:{
			columns:{
				type:"follows_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			distinct:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	follows_aggregate_order_by:{
		count:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		max:{
			type:"follows_max_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		min:{
			type:"follows_min_order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	follows_arr_rel_insert_input:{
		data:{
			type:"follows_insert_input",
			array:true,
			arrayRequired:true,
			required:true
		}
	},
	follows_bool_exp:{
		_and:{
			type:"follows_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		_not:{
			type:"follows_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"follows_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		created_at:{
			type:"timestamptz_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		follower_id:{
			type:"uuid_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"timestamptz_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"users_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		userByUserId:{
			type:"users_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"uuid_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	follows_insert_input:{
		created_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		follower_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"users_obj_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		userByUserId:{
			type:"users_obj_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	follows_max_order_by:{
		created_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		follower_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	follows_min_order_by:{
		created_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		follower_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	follows_order_by:{
		created_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		follower_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"users_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		userByUserId:{
			type:"users_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	follows_select_column: "enum",
	follows_set_input:{
		created_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		follower_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	mutation_root:{
		delete_follows:{
			where:{
				type:"follows_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_posts:{
			where:{
				type:"posts_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_users:{
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_users_by_pk:{
			id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		insert_follows:{
			objects:{
				type:"follows_insert_input",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		insert_follows_one:{
			object:{
				type:"follows_insert_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		insert_posts:{
			objects:{
				type:"posts_insert_input",
				array:true,
				arrayRequired:true,
				required:true
			}
		},
		insert_posts_one:{
			object:{
				type:"posts_insert_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		insert_users:{
			objects:{
				type:"users_insert_input",
				array:true,
				arrayRequired:true,
				required:true
			},
			on_conflict:{
				type:"users_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_users_one:{
			object:{
				type:"users_insert_input",
				array:false,
				arrayRequired:false,
				required:true
			},
			on_conflict:{
				type:"users_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		update_follows:{
			_set:{
				type:"follows_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"follows_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_posts:{
			_set:{
				type:"posts_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"posts_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_users:{
			_set:{
				type:"users_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_users_by_pk:{
			_set:{
				type:"users_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			pk_columns:{
				type:"users_pk_columns_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	order_by: "enum",
	posts_aggregate_fields:{
		count:{
			columns:{
				type:"posts_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			distinct:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	posts_aggregate_order_by:{
		count:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		max:{
			type:"posts_max_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		min:{
			type:"posts_min_order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	posts_arr_rel_insert_input:{
		data:{
			type:"posts_insert_input",
			array:true,
			arrayRequired:true,
			required:true
		}
	},
	posts_bool_exp:{
		_and:{
			type:"posts_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		_not:{
			type:"posts_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"posts_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		content:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"timestamptz_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"uuid_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"timestamptz_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"users_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"uuid_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	posts_insert_input:{
		content:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"users_obj_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	posts_max_order_by:{
		content:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	posts_min_order_by:{
		content:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	posts_order_by:{
		content:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"users_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	posts_select_column: "enum",
	posts_set_input:{
		content:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	query_root:{
		follows:{
			distinct_on:{
				type:"follows_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"follows_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"follows_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		follows_aggregate:{
			distinct_on:{
				type:"follows_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"follows_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"follows_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		posts:{
			distinct_on:{
				type:"posts_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"posts_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"posts_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		posts_aggregate:{
			distinct_on:{
				type:"posts_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"posts_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"posts_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		users:{
			distinct_on:{
				type:"users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"users_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		users_aggregate:{
			distinct_on:{
				type:"users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"users_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		users_by_pk:{
			id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	subscription_root:{
		follows:{
			distinct_on:{
				type:"follows_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"follows_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"follows_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		follows_aggregate:{
			distinct_on:{
				type:"follows_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"follows_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"follows_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		posts:{
			distinct_on:{
				type:"posts_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"posts_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"posts_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		posts_aggregate:{
			distinct_on:{
				type:"posts_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"posts_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"posts_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		users:{
			distinct_on:{
				type:"users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"users_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		users_aggregate:{
			distinct_on:{
				type:"users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"users_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"users_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		users_by_pk:{
			id:{
				type:"uuid",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	timestamptz: "String",
	timestamptz_comparison_exp:{
		_eq:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"timestamptz",
			array:true,
			arrayRequired:false,
			required:true
		},
		_is_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"timestamptz",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	users:{
		follows:{
			distinct_on:{
				type:"follows_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"follows_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"follows_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		follows_aggregate:{
			distinct_on:{
				type:"follows_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"follows_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"follows_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		posts:{
			distinct_on:{
				type:"posts_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"posts_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"posts_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		posts_aggregate:{
			distinct_on:{
				type:"posts_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"posts_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"posts_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	users_aggregate_fields:{
		count:{
			columns:{
				type:"users_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			distinct:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	users_bool_exp:{
		_and:{
			type:"users_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		_not:{
			type:"users_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"users_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		avatar_url:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"timestamptz_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		first_name:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		follows:{
			type:"follows_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"uuid_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		last_name:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		password:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		posts:{
			type:"posts_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"timestamptz_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_constraint: "enum",
	users_insert_input:{
		avatar_url:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		first_name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		follows:{
			type:"follows_arr_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		last_name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		password:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		posts:{
			type:"posts_arr_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_obj_rel_insert_input:{
		data:{
			type:"users_insert_input",
			array:false,
			arrayRequired:false,
			required:true
		},
		on_conflict:{
			type:"users_on_conflict",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_on_conflict:{
		constraint:{
			type:"users_constraint",
			array:false,
			arrayRequired:false,
			required:true
		},
		update_columns:{
			type:"users_update_column",
			array:true,
			arrayRequired:true,
			required:true
		},
		where:{
			type:"users_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_order_by:{
		avatar_url:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		first_name:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		follows_aggregate:{
			type:"follows_aggregate_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		last_name:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		password:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		posts_aggregate:{
			type:"posts_aggregate_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_pk_columns_input:{
		id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	users_select_column: "enum",
	users_set_input:{
		avatar_url:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		created_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		first_name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		last_name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		password:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	users_update_column: "enum",
	uuid: "String",
	uuid_comparison_exp:{
		_eq:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"uuid",
			array:true,
			arrayRequired:false,
			required:true
		},
		_is_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"uuid",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"uuid",
			array:true,
			arrayRequired:false,
			required:true
		}
	}
}

export const ReturnTypes: Record<string,any> = {
	cached:{
		ttl:"Int",
		refresh:"Boolean"
	},
	follows:{
		created_at:"timestamptz",
		follower_id:"uuid",
		updated_at:"timestamptz",
		user:"users",
		userByUserId:"users",
		user_id:"uuid"
	},
	follows_aggregate:{
		aggregate:"follows_aggregate_fields",
		nodes:"follows"
	},
	follows_aggregate_fields:{
		count:"Int",
		max:"follows_max_fields",
		min:"follows_min_fields"
	},
	follows_max_fields:{
		created_at:"timestamptz",
		follower_id:"uuid",
		updated_at:"timestamptz",
		user_id:"uuid"
	},
	follows_min_fields:{
		created_at:"timestamptz",
		follower_id:"uuid",
		updated_at:"timestamptz",
		user_id:"uuid"
	},
	follows_mutation_response:{
		affected_rows:"Int",
		returning:"follows"
	},
	mutation_root:{
		delete_follows:"follows_mutation_response",
		delete_posts:"posts_mutation_response",
		delete_users:"users_mutation_response",
		delete_users_by_pk:"users",
		insert_follows:"follows_mutation_response",
		insert_follows_one:"follows",
		insert_posts:"posts_mutation_response",
		insert_posts_one:"posts",
		insert_users:"users_mutation_response",
		insert_users_one:"users",
		update_follows:"follows_mutation_response",
		update_posts:"posts_mutation_response",
		update_users:"users_mutation_response",
		update_users_by_pk:"users"
	},
	posts:{
		content:"String",
		created_at:"timestamptz",
		id:"uuid",
		updated_at:"timestamptz",
		user:"users",
		user_id:"uuid"
	},
	posts_aggregate:{
		aggregate:"posts_aggregate_fields",
		nodes:"posts"
	},
	posts_aggregate_fields:{
		count:"Int",
		max:"posts_max_fields",
		min:"posts_min_fields"
	},
	posts_max_fields:{
		content:"String",
		created_at:"timestamptz",
		id:"uuid",
		updated_at:"timestamptz",
		user_id:"uuid"
	},
	posts_min_fields:{
		content:"String",
		created_at:"timestamptz",
		id:"uuid",
		updated_at:"timestamptz",
		user_id:"uuid"
	},
	posts_mutation_response:{
		affected_rows:"Int",
		returning:"posts"
	},
	query_root:{
		follows:"follows",
		follows_aggregate:"follows_aggregate",
		posts:"posts",
		posts_aggregate:"posts_aggregate",
		users:"users",
		users_aggregate:"users_aggregate",
		users_by_pk:"users"
	},
	subscription_root:{
		follows:"follows",
		follows_aggregate:"follows_aggregate",
		posts:"posts",
		posts_aggregate:"posts_aggregate",
		users:"users",
		users_aggregate:"users_aggregate",
		users_by_pk:"users"
	},
	users:{
		avatar_url:"String",
		created_at:"timestamptz",
		email:"String",
		first_name:"String",
		follows:"follows",
		follows_aggregate:"follows_aggregate",
		id:"uuid",
		last_name:"String",
		password:"String",
		posts:"posts",
		posts_aggregate:"posts_aggregate",
		updated_at:"timestamptz"
	},
	users_aggregate:{
		aggregate:"users_aggregate_fields",
		nodes:"users"
	},
	users_aggregate_fields:{
		count:"Int",
		max:"users_max_fields",
		min:"users_min_fields"
	},
	users_max_fields:{
		avatar_url:"String",
		created_at:"timestamptz",
		email:"String",
		first_name:"String",
		id:"uuid",
		last_name:"String",
		password:"String",
		updated_at:"timestamptz"
	},
	users_min_fields:{
		avatar_url:"String",
		created_at:"timestamptz",
		email:"String",
		first_name:"String",
		id:"uuid",
		last_name:"String",
		password:"String",
		updated_at:"timestamptz"
	},
	users_mutation_response:{
		affected_rows:"Int",
		returning:"users"
	}
}