[package]
edition = "2021"
name = "rs_physic_play"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {version = "*"}
bincode = {version = "*"}
draw = {version = "*"}
rapier2d = {version = "*", features = ["enhanced-determinism", "serde-serialize"]}
serde = {version = "*"}
sha256 = {version = "*"}
