version: '3.1'

services:
  pg:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev-db
      
  redis:
    image: redis
    ports:
      - "6379:6379"

  metabase-app:
    image: metabase/metabase
    restart: always
    ports:
      - "3001:3000"
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - /home/app/metabase-data:/metabase-data
   