[package]
edition = "2018"
name = "port-scan"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
clap = "2.33"
futures = "0.3"
tokio = {version = "1", features = ["full"]}
