// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simple.proto

package messasing

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MSG_TYPE int32

const (
	MSG_TYPE_PING MSG_TYPE = 0
	MSG_TYPE_PONG MSG_TYPE = 1
)

var MSG_TYPE_name = map[int32]string{
	0: "PING",
	1: "PONG",
}

var MSG_TYPE_value = map[string]int32{
	"PING": 0,
	"PONG": 1,
}

func (x MSG_TYPE) String() string {
	return proto.EnumName(MSG_TYPE_name, int32(x))
}

func (MSG_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5ffd045dd4d042c1, []int{0}
}

type PingBody struct {
	Nounce               int32    `protobuf:"varint,1,opt,name=nounce,proto3" json:"nounce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingBody) Reset()         { *m = PingBody{} }
func (m *PingBody) String() string { return proto.CompactTextString(m) }
func (*PingBody) ProtoMessage()    {}
func (*PingBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ffd045dd4d042c1, []int{0}
}

func (m *PingBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingBody.Unmarshal(m, b)
}
func (m *PingBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingBody.Marshal(b, m, deterministic)
}
func (m *PingBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingBody.Merge(m, src)
}
func (m *PingBody) XXX_Size() int {
	return xxx_messageInfo_PingBody.Size(m)
}
func (m *PingBody) XXX_DiscardUnknown() {
	xxx_messageInfo_PingBody.DiscardUnknown(m)
}

var xxx_messageInfo_PingBody proto.InternalMessageInfo

func (m *PingBody) GetNounce() int32 {
	if m != nil {
		return m.Nounce
	}
	return 0
}

type PongBody struct {
	Reply                int32    `protobuf:"varint,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongBody) Reset()         { *m = PongBody{} }
func (m *PongBody) String() string { return proto.CompactTextString(m) }
func (*PongBody) ProtoMessage()    {}
func (*PongBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ffd045dd4d042c1, []int{1}
}

func (m *PongBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongBody.Unmarshal(m, b)
}
func (m *PongBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongBody.Marshal(b, m, deterministic)
}
func (m *PongBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongBody.Merge(m, src)
}
func (m *PongBody) XXX_Size() int {
	return xxx_messageInfo_PongBody.Size(m)
}
func (m *PongBody) XXX_DiscardUnknown() {
	xxx_messageInfo_PongBody.DiscardUnknown(m)
}

var xxx_messageInfo_PongBody proto.InternalMessageInfo

func (m *PongBody) GetReply() int32 {
	if m != nil {
		return m.Reply
	}
	return 0
}

type AwesomeMessage struct {
	Type      MSG_TYPE            `protobuf:"varint,1,opt,name=type,proto3,enum=messasing.MSG_TYPE" json:"type,omitempty"`
	Id        int64               `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt int64               `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Extra     map[string]*any.Any `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Types that are valid to be assigned to Body:
	//	*AwesomeMessage_PingBody
	//	*AwesomeMessage_PongBody
	Body                 isAwesomeMessage_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AwesomeMessage) Reset()         { *m = AwesomeMessage{} }
func (m *AwesomeMessage) String() string { return proto.CompactTextString(m) }
func (*AwesomeMessage) ProtoMessage()    {}
func (*AwesomeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ffd045dd4d042c1, []int{2}
}

func (m *AwesomeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AwesomeMessage.Unmarshal(m, b)
}
func (m *AwesomeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AwesomeMessage.Marshal(b, m, deterministic)
}
func (m *AwesomeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AwesomeMessage.Merge(m, src)
}
func (m *AwesomeMessage) XXX_Size() int {
	return xxx_messageInfo_AwesomeMessage.Size(m)
}
func (m *AwesomeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AwesomeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AwesomeMessage proto.InternalMessageInfo

func (m *AwesomeMessage) GetType() MSG_TYPE {
	if m != nil {
		return m.Type
	}
	return MSG_TYPE_PING
}

func (m *AwesomeMessage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AwesomeMessage) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *AwesomeMessage) GetExtra() map[string]*any.Any {
	if m != nil {
		return m.Extra
	}
	return nil
}

type isAwesomeMessage_Body interface {
	isAwesomeMessage_Body()
}

type AwesomeMessage_PingBody struct {
	PingBody *PingBody `protobuf:"bytes,5,opt,name=pingBody,proto3,oneof"`
}

type AwesomeMessage_PongBody struct {
	PongBody *PongBody `protobuf:"bytes,6,opt,name=pongBody,proto3,oneof"`
}

func (*AwesomeMessage_PingBody) isAwesomeMessage_Body() {}

func (*AwesomeMessage_PongBody) isAwesomeMessage_Body() {}

func (m *AwesomeMessage) GetBody() isAwesomeMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *AwesomeMessage) GetPingBody() *PingBody {
	if x, ok := m.GetBody().(*AwesomeMessage_PingBody); ok {
		return x.PingBody
	}
	return nil
}

func (m *AwesomeMessage) GetPongBody() *PongBody {
	if x, ok := m.GetBody().(*AwesomeMessage_PongBody); ok {
		return x.PongBody
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AwesomeMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AwesomeMessage_PingBody)(nil),
		(*AwesomeMessage_PongBody)(nil),
	}
}

func init() {
	proto.RegisterEnum("messasing.MSG_TYPE", MSG_TYPE_name, MSG_TYPE_value)
	proto.RegisterType((*PingBody)(nil), "messasing.PingBody")
	proto.RegisterType((*PongBody)(nil), "messasing.PongBody")
	proto.RegisterType((*AwesomeMessage)(nil), "messasing.AwesomeMessage")
	proto.RegisterMapType((map[string]*any.Any)(nil), "messasing.AwesomeMessage.ExtraEntry")
}

func init() { proto.RegisterFile("simple.proto", fileDescriptor_5ffd045dd4d042c1) }

var fileDescriptor_5ffd045dd4d042c1 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4b, 0x4b, 0xc3, 0x40,
	0x10, 0xc7, 0x9b, 0x27, 0xe9, 0x54, 0x4a, 0x59, 0x8b, 0xc4, 0x22, 0x12, 0x82, 0x60, 0xe8, 0x61,
	0x8b, 0xf5, 0x22, 0xbd, 0xb5, 0x50, 0xaa, 0x87, 0xd6, 0xb0, 0x7a, 0xf1, 0x24, 0x69, 0xb3, 0x86,
	0x60, 0xba, 0x1b, 0x92, 0x54, 0xdd, 0x8f, 0xeb, 0x37, 0x91, 0xee, 0xa6, 0x2f, 0xbc, 0xcd, 0xce,
	0xfe, 0xfe, 0xf3, 0xf8, 0x0f, 0x9c, 0x95, 0xe9, 0x3a, 0xcf, 0x28, 0xce, 0x0b, 0x5e, 0x71, 0xd4,
	0x5c, 0xd3, 0xb2, 0x8c, 0xca, 0x94, 0x25, 0xbd, 0xcb, 0x84, 0xf3, 0x24, 0xa3, 0x03, 0xf9, 0xb1,
	0xdc, 0x7c, 0x0c, 0x22, 0x26, 0x14, 0xe5, 0xfb, 0xe0, 0x84, 0x29, 0x4b, 0x26, 0x3c, 0x16, 0xe8,
	0x02, 0x6c, 0xc6, 0x37, 0x6c, 0x45, 0x5d, 0xcd, 0xd3, 0x02, 0x8b, 0xd4, 0x2f, 0xdf, 0x03, 0x27,
	0xe4, 0x35, 0xd3, 0x05, 0xab, 0xa0, 0x79, 0x26, 0x6a, 0x44, 0x3d, 0xfc, 0x5f, 0x1d, 0xda, 0xe3,
	0x6f, 0x5a, 0xf2, 0x35, 0x9d, 0x6f, 0xbb, 0x26, 0x14, 0xdd, 0x82, 0x59, 0x89, 0x5c, 0x95, 0x6a,
	0x0f, 0xcf, 0xf1, 0x7e, 0x1a, 0x3c, 0x7f, 0x99, 0xbd, 0xbf, 0xbe, 0x85, 0x53, 0x22, 0x01, 0xd4,
	0x06, 0x3d, 0x8d, 0x5d, 0xdd, 0xd3, 0x02, 0x83, 0xe8, 0x69, 0x8c, 0xae, 0xa0, 0xb9, 0x2a, 0x68,
	0x54, 0xd1, 0x78, 0x5c, 0xb9, 0x86, 0x4c, 0x1f, 0x12, 0x68, 0x04, 0x16, 0xfd, 0xa9, 0x8a, 0xc8,
	0x35, 0x3d, 0x23, 0x68, 0x0d, 0x6f, 0x8e, 0xea, 0x9e, 0x0e, 0x80, 0xa7, 0x5b, 0x6c, 0xca, 0xaa,
	0x42, 0x10, 0x25, 0x41, 0x77, 0xe0, 0xe4, 0xf5, 0xae, 0xae, 0xe5, 0x69, 0x41, 0xeb, 0x64, 0xac,
	0x9d, 0x0d, 0x8f, 0x0d, 0xb2, 0xc7, 0xa4, 0xa4, 0x5e, 0xdd, 0xb5, 0xff, 0x4b, 0xf8, 0x91, 0xa4,
	0x8e, 0x7b, 0x0b, 0x80, 0x43, 0x6b, 0xd4, 0x01, 0xe3, 0x93, 0x2a, 0xb7, 0x9a, 0x64, 0x1b, 0xa2,
	0x3e, 0x58, 0x5f, 0x51, 0xb6, 0xa1, 0x72, 0xe5, 0xd6, 0xb0, 0x8b, 0xd5, 0x71, 0xf0, 0xee, 0x38,
	0x78, 0xcc, 0x04, 0x51, 0xc8, 0x48, 0x7f, 0xd0, 0x26, 0x36, 0x98, 0x4b, 0x1e, 0x8b, 0xfe, 0x35,
	0x38, 0x3b, 0xe7, 0x90, 0x03, 0x66, 0xf8, 0xb4, 0x98, 0x75, 0x1a, 0x32, 0x7a, 0x5e, 0xcc, 0x3a,
	0xda, 0xd2, 0x96, 0x05, 0xee, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x94, 0x70, 0x30, 0xaf, 0x06,
	0x02, 0x00, 0x00,
}
