# Comments in GraphQL are defined with the hash (#) symbol.

type Book {
  id: Int
  title: String
  author: Author
  like: Int
}

type Author {
  id: Int
  name: String
  reputation: Int
  books: [Book]
}

type Query {
  books: [Book]
  bookById(id: Int!): Book
  authors: [Author]
  authorById(id: Int!): Author
}

type Mutation {
  addBook(input: AddBookInput!): UpdateBookMutationResponse
  likeBook(id: Int!): LikeBookMutationResponse
}

input AddBookInput {
  title: String!
  authorId: Int!
}

type UpdateBookMutationResponse {
  code: String!
  success: Boolean!
  message: String!
  book: Book
}

type LikeBookMutationResponse {
  code: String!
  success: Boolean!
  message: String!
  book: Book
  author: Author
}
