version: "3"
services:
  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:4
    volumes:
      - /data/db/mongo
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    expose:
      - 27017
    ports:
      - 27017:27017

  mongosetup:
    image: mongo:4
    depends_on:
      - mongodb
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/scripts/setup.sh"]
