apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node-example-deployment
  labels:
    app: playground
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-example-deployment
    spec:
      containers:
      - name: node-example
        image: gcr.io/weeklyhack-ff068/hello-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DEMO_GREETING
          value: "My name TTin"
        - name: MONGODB_URI
          value: "mongodb://mongodb-service/test"