fn   := _ '\[' _ arg=argList* _ '\]' _ exp=expression _

argList   :=  name=variable _

expression :=  left=expression _ op='\+' _ right=term
               | left=expression _ op='-' _ right=term
               | term

term       := left=term _ op='\*' _ right=factor
              | left=term _ op='\/' _ right=factor
              | factor

factor     := imm=num
              | arg=variable
              | '\(' _ exp=expression _ '\)'


variable :='[a-z]+'
num :='[0-9]+'
_ :='\s*'